<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="210372" started-at="2017-12-19T05:38:01Z" finished-at="2017-12-19T05:41:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="210372" started-at="2017-12-19T05:38:01Z" finished-at="2017-12-19T05:41:31Z">
      <class name="com.smartquote.automation.SQ_Standalone_DealCreate">
        <test-method status="FAIL" signature="sqExternalDealCreation()[pri:0, instance:com.smartquote.automation.SQ_Standalone_DealCreate@7494f96a]" name="sqExternalDealCreation" duration-ms="208909" started-at="2017-12-19T11:08:01Z" finished-at="2017-12-19T11:11:30Z">
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[C:\Users\aluru\Desktop\SQResults\SQ_Reseller_Results.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: C:\Users\aluru\Desktop\SQResults\SQ_Reseller_Results.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.smartquote.automation.excelutilities.SQExcelUtilities.SQ_ExcelWrite(SQExcelUtilities.java:108)
	at com.smartquote.automation.SQ_Standalone_DealCreate.sqExternalDealCreation(SQ_Standalone_DealCreate.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sqExternalDealCreation -->
        <test-method status="SKIP" signature="sqInternalDealCreation()[pri:0, instance:com.smartquote.automation.SQ_Standalone_DealCreate@7494f96a]" name="sqInternalDealCreation" duration-ms="0" started-at="2017-12-19T11:11:31Z" depends-on-methods="com.smartquote.automation.SQ_Standalone_DealCreate.sqExternalDealCreation" finished-at="2017-12-19T11:11:31Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SQ_Standalone_DealCreate.sqInternalDealCreation()[pri:0, instance:com.smartquote.automation.SQ_Standalone_DealCreate@7494f96a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SQ_Standalone_DealCreate.sqInternalDealCreation()[pri:0, instance:com.smartquote.automation.SQ_Standalone_DealCreate@7494f96a] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sqInternalDealCreation -->
      </class> <!-- com.smartquote.automation.SQ_Standalone_DealCreate -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
